apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: myspace
spec:
  limits:
  - default:
      cpu: 50m
      memory: 200Mi
    defaultRequest:
      cpu: 20m
      memory: 100Mi
    type: Container
