kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-3
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi