apiVersion: v1  
kind: PersistentVolume  
metadata:
  name: pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: "/localstorage"