apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-example
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      containers:
      - name: hpa-example
        image: gcr.io/google_containers/hpa-example
        ports:
        - name: http-port
          containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-example
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: http-port
    protocol: TCP
  selector:
    app: hpa-example
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-example-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-example
  minReplicas: 1  # eger ehtiyac olarsa minimum 1 dene pod elave et, eger deploymentde replica 3 olaraq qeyd olunubsa ve deployment yuk altinda islemirse onda 1 dene replika olaraq calisacaqdir deployment
  maxReplicas: 10  # maksimum scale olunacaq pod sayisi 10 olsun
  targetCPUUtilizationPercentage: 50  # cpu 50%i kecerse autoscaling olsun
