apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: quay.io/muradsamadov/pythonapp:v1
        ports:
        - name: flask-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: flask-port
          initialDelaySeconds: 15  # 15 saniye gozledikden sonra ilk defe isleme
          timeoutSeconds: 30  # 30 saniyede cavab gelmezse timeout-a dus
          periodSeconds: 5  # her 5 saniyeden bir kontrol et
          failureThreshold: 1  # 1 defe fail olmaga icaze ver , daha cox olarsa podu fail et
