apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: front-end
    team: developer
spec:
  restartPolicy: OnFailure
  containers:
    - name: nginx
      image: quay.io/muradsamadov/ubuntu
      command: ['sh', '-c', 'echo "Hello World" && sleep 10']