apiVersion: v1
kind: Pod
metadata:
  name: secretpodvolume
spec:
  containers:
  - name: secretcontainer
    image: quay.io/muradsamadov/k8s:blue
    volumeMounts:
    - mountPath: /secret
      name: secret-vol 
  volumes:
  - name: secret-vol
    secret:
      secretName: mysecret-to-file

---
apiVersion: v1
kind: Pod
metadata:
  name: secretpodenv
spec:
  containers:
  - name: secretcontainer
    image: quay.io/muradsamadov/k8s:blue
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: mysecret-to-file
          key: db_username
    - name: password
      valueFrom:
        secretKeyRef:
          name: mysecret-to-file
          key: db_password
    - name: server
      valueFrom:
        secretKeyRef:
          name: mysecret-to-file
          key: db_server
    
---
apiVersion: v1
kind: Pod
metadata:
  name: secretpodenvall
spec:
  containers:
  - name: secretcontainer
    image: quay.io/muradsamadov/k8s:blue
    envFrom:
    - secretRef:
        name: mysecret-to-file