apiVersion: v1
kind: Pod
metadata:
  name: envpod
  labels:
    app: frontend
spec:
  containers:
  - name: envpod
    image: quay.io/muradsamadov/env
    ports:
    - containerPort: 80
    env:
    - name: USER
      value: "Murad"
    - name: database
      value: "localhost"   